In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np

test = pd.read_csv('tetrahymena2.tsv', sep = '\t')
test.query('diameter<= 19.2 & diameter >= 26.0')
filtered = test[test['diameter'] > 26.0] , test[test['diameter'] < 19.2]

(     conc   diameter  culture
 31  10977  26.244236       32
 80  13412  26.060537       30
 82  10872  26.364611       32,
       conc   diameter  culture
 83  630111  19.152828       33)